version: "3.9"

services:
   app:
     container_name: "php_runner"
     build: .
     ports:
      - "8000:80"       # Browser: http://localhost:8000
     volumes:
      - .:/var/www/html
     restart: unless-stopped
